# Generated by Django 4.2.6 on 2023-10-05 13:46

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[school.validators.validate_school_year])),
            ],
        ),
    ]
