# Generated by Django 4.2.6 on 2023-10-06 02:06

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.PositiveIntegerField(unique=True, validators=[school.validators.validate_school_year]),
        ),
    ]
