# Generated by Django 4.2.6 on 2023-10-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolyear_id_alter_schoolyear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit', models.PositiveSmallIntegerField()),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='school.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=3)),
                ('enrollment_start_date', models.DateField()),
                ('enrollment_end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('courses', models.ManyToManyField(related_name='semesters', to='school.course')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='school.schoolyear')),
            ],
            options={
                'unique_together': {('name', 'school_year')},
            },
        ),
    ]
