# Generated by Django 4.2.7 on 2023-11-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'section', 'semester', 'school_year')},
        ),
    ]
