# Generated by Django 4.2.6 on 2023-10-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.department'),
            preserve_default=False,
        ),
    ]
