# Generated by Django 4.2.6 on 2023-10-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='latest_semester',
            field=models.BooleanField(default=False),
        ),
    ]
