# Generated by Django 4.2.6 on 2023-10-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_latest_semester_semester_current_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='current_semester',
            new_name='is_current',
        ),
    ]
