# Generated by Django 4.2.6 on 2023-10-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_departmentaddress_departmentcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentaddress',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='departmentaddress', serialize=False, to='school.department'),
        ),
    ]
