# Generated by Django 4.2.6 on 2023-10-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_departmentaddress_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentcontact', to='school.department'),
        ),
    ]
