# Generated by Django 4.2.6 on 2023-10-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_building_addresss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='addresss',
        ),
    ]
