# Generated by Django 4.2.6 on 2023-10-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school', '0014_remove_building_addresss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresss',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='only_for_frontend', to='contenttypes.contenttype'),
        ),
    ]
