# Generated by Django 4.2.6 on 2023-11-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_addresss_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('community', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BuildingAddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.building')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Addresss',
        ),
    ]
