# Generated by Django 4.2.6 on 2023-11-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_buildingaddress_delete_addresss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingaddress',
            name='BuildingAddress',
        ),
        migrations.AddField(
            model_name='buildingaddress',
            name='building',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='building', serialize=False, to='school.building'),
            preserve_default=False,
        ),
    ]
