# Generated by Django 4.2.6 on 2023-11-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_buildingaddress_buildingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingaddress',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buildingaddress', serialize=False, to='school.building'),
        ),
    ]
