# Generated by Django 4.2.6 on 2023-11-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_buildingaddress_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='school.building')),
            ],
        ),
    ]
