# Generated by Django 4.2.6 on 2023-11-03 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school', '0020_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('SCHOLAR', 'Scholarship'), ('ACADEMIC', 'Academic'), ('MEDICAL', 'Medical'), ('EMP', 'Employeement'), ('PROMO', 'Promotion'), ('WARNING', 'Warning'), ('SUSPEN', 'Suspension'), ('JOB', 'Job Related'), ('LEAVE', 'Leave')], max_length=8)),
                ('achievement_date', models.DateField()),
                ('institution_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='school/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
