# Generated by Django 4.2.6 on 2023-11-03 06:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('SCHOLAR', 'Scholarship'), ('ACADEMIC', 'Academic'), ('MEDICAL', 'Medical'), ('EMP', 'Employeement'), ('PROMO', 'Promotion'), ('WARNING', 'Warning'), ('SUSPEN', 'Suspension'), ('JOB', 'Job Related'), ('LEAVE', 'Leave')], max_length=8)),
                ('institution_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='school/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('date_achieved', models.DateField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
