# Generated by Django 4.2.6 on 2023-11-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_semesterdocument_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterdocument',
            name='year',
            field=models.DateField(auto_now_add=True, default='2023-11-03'),
            preserve_default=False,
        ),
    ]
