# Generated by Django 4.2.7 on 2023-11-03 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active'),
        ('school', '0024_delete_semesterdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('religion', models.CharField(choices=[('C', 'Christian'), ('M', 'Muslim'), ('N', 'None')], max_length=1)),
                ('image', models.ImageField(upload_to='school/images')),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=1)),
                ('employment_status', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time')], max_length=2)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('term_of_reference', models.FileField(upload_to='school/TOR', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='school.department')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='school.office')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to='school.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
