# Generated by Django 4.2.7 on 2023-11-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='person',
            new_name='user',
        ),
    ]
