# Generated by Django 4.2.7 on 2023-11-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1),
        ),
    ]
