# Generated by Django 4.2.7 on 2023-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_employeeaddress_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0776467890', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeContact',
        ),
    ]
