# Generated by Django 4.2.7 on 2023-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_employee_phone_delete_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level_of_education',
            field=models.CharField(choices=[('HSD', 'High Sch Diploma'), ('TRD', 'Trade Sch Certificate'), ('BSC', 'Barchelor Degree'), ('MSC', 'Master Degree'), ('PHD', 'Doctorate Degree')], default='BSC', max_length=3),
            preserve_default=False,
        ),
    ]
