# Generated by Django 4.2.7 on 2023-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_employee_level_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level_of_education',
            field=models.CharField(choices=[('HSD', 'High Sch Diploma'), ('TRD', 'Trade Sch Certificate'), ('BSC', 'Bachelor Degree'), ('MSC', 'Master Degree'), ('PHD', 'Doctorate Degree')], max_length=3),
        ),
    ]
