# Generated by Django 4.2.7 on 2023-11-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('None', 'None')], max_length=9),
        ),
    ]
