# Generated by Django 4.2.7 on 2023-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_alter_employee_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level_of_education',
            field=models.CharField(choices=[('High Sch Diploma', 'High Sch Diploma'), ('Trade Sch Certificate', 'Trade Sch Certificate'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree'), ('Doctorate Degree', 'Doctorate Degree')], max_length=21),
        ),
    ]
