# Generated by Django 4.2.7 on 2023-11-10 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import school.models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active'),
        ('school', '0036_alter_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('None', 'None')], max_length=9)),
                ('image', models.ImageField(upload_to='school/images', validators=[school.validators.validate_file_size])),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=7)),
                ('employment_status', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=9)),
                ('level_of_education', models.CharField(choices=[('High Sch Diploma', 'High Sch Diploma'), ('Trade Sch Certificate', 'Trade Sch Certificate'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree'), ('Doctorate Degree', 'Doctorate Degree')], max_length=21)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('term_of_reference', models.FileField(upload_to=school.models.tor_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='school.department')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='school.office')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to='school.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
