# Generated by Django 4.2.7 on 2023-11-10 12:09

from django.db import migrations, models
import django.db.models.deletion
import school.models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAddress',
            fields=[
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('community', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacheraddress', serialize=False, to='school.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to=school.models.image_upload_path, validators=[school.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to=school.models.image_upload_path, validators=[school.validators.validate_file_size]),
        ),
    ]
