# Generated by Django 4.2.7 on 2023-11-11 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.utility
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active'),
        ('school', '0038_teacheraddress_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='school.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('level', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('None', 'None')], max_length=9)),
                ('image', models.ImageField(upload_to=school.utility.image_upload_path, validators=[school.validators.validate_file_size])),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.department')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.major')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentees', to='school.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
