# Generated by Django 4.2.7 on 2023-11-12 15:28

from django.db import migrations, models
import school.utility


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_studentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=school.utility.student_number_generator, max_length=255),
        ),
    ]
