# Generated by Django 4.2.7 on 2023-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_alter_employee_user_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='school.department'),
        ),
    ]
