# Generated by Django 4.2.7 on 2023-11-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_teach'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teach',
            unique_together={('teacher', 'course', 'section', 'semester', 'school_year')},
        ),
    ]
