# Generated by Django 4.2.7 on 2023-11-24 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_teach_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'section', 'semester', 'school_year')},
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(10, message='Points cannot be grater than 10!')])),
                ('quiz', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(10, message='Points cannot be grater than 10!')])),
                ('assignment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(5, message='Points cannot be grater than 5!')])),
                ('midterm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(25, message='Points cannot be grater than 25!')])),
                ('project', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(15, message='Points cannot be grater than 15!')])),
                ('final', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Points cannot be less than 0!'), django.core.validators.MaxValueValidator(35, message='Points cannot be grater than 35!')])),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.course')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='school.student')),
            ],
        ),
    ]
