# Generated by Django 4.2.7 on 2023-11-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_alter_grade_assignment_alter_grade_attendance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'school_year', 'semester', 'course', 'section')},
        ),
    ]
